global:
  # How frequently to scrape targets by default.
  scrape_interval: 5s

  # How frequently to evaluate rules.
  evaluation_interval: 10s 

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    addresses: Ethereum Addresses

scrape_configs:
  - job_name: active-ethereum-addresses
    static_configs:
      - targets: ['localhost:9090']
      - targets: ['docker.for.mac.localhost:3030']
      